### ISSUE TITLE
Running the example 

### ISSUE THREAD

**Issue by nick-torenvliet** [strongio/torch-kalman#41]
Hi - just cloned the repo and tried to run the example air_quality_example.py

To get df_aq_weekly to match what the web page showed, I had to change the data pre-processing at the start... something to do with chnages to datetime. 

These are my changes:
df_aq_weekly = df_aq.assign(date= lambda df: df['time'] - pd.to_timedelta(df['time'].dt.dayofweek, unit='d'))
df_aq_weekly['date']= pd.to_datetime(pd.to_datetime(df_aq_weekly['date']).dt.date)
df_aq_weekly = df_aq_weekly.drop(columns= ['year','month','day','hour','time','No','NO2', 'wd','WSPM', 'RAIN', 'PM2p5', 'CO', 'O3'])
df_aq_weekly = df_aq_weekly.groupby(['date','station']).agg('mean').reset_index()
df_aq_weekly = df_aq_weekly.sort_values(['station','date'])
df_aq_weekly = df_aq_weekly.reset_index()
df_aq_weekly6 = df_aq_weekly.drop(columns= ['index'])

Then running the code gave me the following error... not sure how to fix.... 

/python /home/torenvln/.vscode/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 43453 -- /home/torenvln/Git/torch-kalman/examples/air_quality_example.py 
/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/_check.py:172: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/torenvln/.vscode/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/torenvln/.vscode/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/torenvln/.vscode/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/torenvln/.vscode/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/torenvln/.vscode/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/torenvln/.vscode/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/torenvln/Git/torch-kalman/examples/air_quality_example.py", line 136, in <module>
    kf_first = KalmanFilter(
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch_kalman/kalman_filter/base.py", line 68, in __init__
    self.script_module = torch.jit.script(self.script_module)
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/_script.py", line 1284, in script
    return torch.jit._recursive.create_script_module(
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/_recursive.py", line 480, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/_script.py", line 614, in _construct
    init_fn(script_module)
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/_recursive.py", line 520, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/_recursive.py", line 546, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/_recursive.py", line 397, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/_recursive.py", line 898, in compile_unbound_method
    create_methods_and_properties_from_stubs(concrete_type, (stub,), ())
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/_recursive.py", line 397, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/_recursive.py", line 898, in compile_unbound_method
    create_methods_and_properties_from_stubs(concrete_type, (stub,), ())
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/_recursive.py", line 397, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/_recursive.py", line 898, in compile_unbound_method
    create_methods_and_properties_from_stubs(concrete_type, (stub,), ())
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/_recursive.py", line 397, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/_recursive.py", line 867, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/_script.py", line 1338, in script
    ast = get_jit_def(obj, obj.__name__)
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/frontend.py", line 297, in get_jit_def
    return build_def(parsed_def.ctx, fn_def, type_line, def_name, self_name=self_name, pdt_arg_types=pdt_arg_types)
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/frontend.py", line 335, in build_def
    param_list = build_param_list(ctx, py_def.args, self_name, pdt_arg_types)
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/jit/frontend.py", line 370, in build_param_list
    raise NotSupportedError(ctx_range, _vararg_kwarg_err)
torch.jit.frontend.NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch/_linalg_utils.py", line 103
def solve(input: Tensor, A: Tensor, *, out=None) -> Tuple[Tensor, Tensor]:
                                           ~~~~ <--- HERE
    raise RuntimeError(
        "This function was deprecated since version 1.9 and is now removed. Please use the `torch.linalg.solve` function instead.",
'GaussianStep.kalman_gain' is being compiled since it was called from 'GaussianStep._update'
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch_kalman/kalman_filter/gaussian.py", line 66
    def _update(self, input: Tensor, mean: Tensor, cov: Tensor, H: Tensor, R: Tensor) -> Tuple[Tensor, Tensor]:
        # this should just be part of `update()`, but recursive calls not currently supported in torchscript
        K = self.kalman_gain(cov=cov, H=H, R=R)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        measured_mean = H.matmul(mean.unsqueeze(2)).squeeze(2)
        new_mean = mean + K.matmul((input - measured_mean).unsqueeze(2)).squeeze(2)
'GaussianStep._update' is being compiled since it was called from 'GaussianStep.update'
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch_kalman/kalman_filter/gaussian.py", line 46
            for groups, val_idx in get_nan_groups(isnan):
                if val_idx is None:
                    new_mean[groups], new_cov[groups] = self._update(
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        input=input[groups], mean=mean[groups], cov=cov[groups], H=H[groups], R=R[groups]
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                    )
                else:
'GaussianStep.update' is being compiled since it was called from 'GaussianStep.forward'
  File "/home/torenvln/Interpreters/p3/lib/python3.10/site-packages/torch_kalman/kalman_filter/gaussian.py", line 24
                F: Tensor,
                Q: Tensor) -> Tuple[Tensor, Tensor]:
        mean, cov = self.update(input, mean, cov, H=H, R=R)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        return self.predict(mean, cov, F=F, Q=Q)

**Comment by nick-torenvliet** [comment]
I could give you a listing of my package levels... but they are all pretty much the most recent. 

Nick

**Comment by jwdink** [comment]
Hey @nick-torenvliet , this package isn't maintained anymore, please check out https://github.com/strongio/torchcast
